# Generated by Django 3.1.7 on 2021-05-03 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("P", "Partner"),
                            ("T", "Test"),
                            ("D", "Disabled"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("rating", models.FloatField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.PositiveIntegerField()),
                ("message", picklefield.fields.PickledObjectField(editable=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Телефонный номер должен быть в формате: '+999999999' и не длиннее 15 символов.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "is_phone_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="Телефон подтвержден"
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "avatar",
                    sorl.thumbnail.fields.ImageField(
                        blank=True, upload_to="user_profile/", verbose_name="Аватар"
                    ),
                ),
                (
                    "subsciber",
                    models.ManyToManyField(
                        blank=True, to="main.Subscriptions", verbose_name="Подписки"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField()),
                ("weight", models.FloatField(blank=True, null=True)),
                ("manufacturer", models.CharField(max_length=80)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("rating", models.FloatField(default=5.0)),
                ("price", models.FloatField(default=0)),
                ("discount", models.FloatField(default=0)),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        blank=True, upload_to="goods/", verbose_name="Фото"
                    ),
                ),
                ("creation_date", models.DateField(verbose_name="Дата создания")),
                ("views_counter", models.IntegerField(default=0)),
                ("in_stock", models.IntegerField(default=0)),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "is_archive",
                    models.BooleanField(default=False, verbose_name="В архиве"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.category",
                        verbose_name="the related category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.seller",
                        verbose_name="the related seller",
                    ),
                ),
                ("tags", models.ManyToManyField(to="main.Tag")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
