# Generated by Django 3.1.7 on 2021-03-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="goods",
            name="rating",
            field=models.FloatField(default=5.0),
        ),
    ]
