# Generated by Django 3.1.7 on 2021-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20210328_1405"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="discount",
            field=models.FloatField(default=0),
        ),
    ]
