# Generated by Django 3.1.7 on 2021-05-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210503_2351'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE VIEW main_goodsshort \
             AS SELECT \
                id,\
                name,\
                description,\
                manufacturer,\
                tags,\
                price,\
                creation_date,\
                views_counter,\
                in_stock,\
                is_published,\
                is_archive\
             FROM main_goods"
        )
    ]

    