# Generated by Django 3.1.7 on 2021-05-04 19:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210504_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=80)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40, null=True), blank=True, null=True, size=None)),
                ('price', models.FloatField(default=0)),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('views_counter', models.IntegerField(default=0)),
                ('in_stock', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_archive', models.BooleanField(default=False, verbose_name='В архиве')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
