# Generated by Django 3.1.7 on 2021-04-08 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть в формате: '+999999999' и не длиннее 15 символов.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
