# Generated by Django 3.1.7 on 2021-04-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_auto_20210408_1726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                max_length=1,
                null=True,
            ),
        ),
    ]
