# Generated by Django 3.1.7 on 2021-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_auto_20210408_2021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
