# Generated by Django 3.1.7 on 2021-04-09 13:42

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210409_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='media/goods/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='media/user_profile/', verbose_name='Аватар'),
        ),
    ]
