# Generated by Django 3.1.7 on 2021-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_auto_20210413_1828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subsciber",
            field=models.ManyToManyField(
                blank=True, to="main.Subscriptions", verbose_name="Подписки"
            ),
        ),
    ]
