# Generated by Django 3.1.7 on 2021-04-14 16:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0015_auto_20210413_1902"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Profile1",
        ),
        migrations.RenameModel(
            old_name="Subscriptions",
            new_name="Subscriptions1",
        ),
    ]
