# Generated by Django 3.1.7 on 2021-04-14 16:04

import django.core.validators
import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_auto_20210414_1902"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Телефонный номер должен быть в формате: '+999999999' и не длиннее 15 символов.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "avatar",
                    sorl.thumbnail.fields.ImageField(
                        blank=True, upload_to="user_profile/", verbose_name="Аватар"
                    ),
                ),
                (
                    "subsciber",
                    models.ManyToManyField(
                        blank=True, to="main.Subscriptions", verbose_name="Подписки"
                    ),
                ),
            ],
        ),
    ]
