# Generated by Django 3.1.7 on 2021-04-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_profile_subscriptions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile1",
        ),
        migrations.DeleteModel(
            name="Subscriptions1",
        ),
    ]
