# Generated by Django 3.1.7 on 2021-04-16 09:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_auto_20210414_1956"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(2021, 4, 16, 12, 6, 36, 932142),
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
