# Generated by Django 3.1.7 on 2021-04-18 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_goods_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='Телефон подтвержден'),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('message', picklefield.fields.PickledObjectField(editable=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
