# Generated by Django 3.1.7 on 2021-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210418_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='views_counter',
            field=models.IntegerField(default=0),
        ),
    ]
