# Generated by Django 3.1.7 on 2021-04-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_goods_views_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="in_stock",
            field=models.IntegerField(default=0),
        ),
    ]
