# Generated by Django 3.1.7 on 2021-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_goods_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
